# Generated by Django 4.2.11 on 2024-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fighter1_name',
            field=models.CharField(default='Fighter 1', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='fighter2_name',
            field=models.CharField(default='Fighter 2', max_length=100),
        ),
    ]
