# Generated by Django 4.2.11 on 2024-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_fighter1_name_post_fighter2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fighter1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fighter2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
