# Generated by Django 4.2.11 on 2024-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_fighter1_name_post_fighter2_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='fighter1_name',
            field=models.CharField(default='Fighter 1', max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='fighter2_name',
            field=models.CharField(default='Fighter 2', max_length=35),
        ),
    ]
