# Generated by Django 4.2.11 on 2024-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About FightVault', max_length=100)),
                ('mission', models.TextField(blank=True)),
                ('values', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
